### PR TITLE
Remove 350.org

### PR DESCRIPTION
**Pull request by bizz84**
## Link URL
https://350.org/

## Description
Building the global grassroots climate movement that can hold our leaders accountable to science and justice.
May be too political for inclusion here.
 
## Checklist

- [x] Only one item/change is in this pull request
- [x] Addition in chronological order (bottom of category) or sorted by most recent date (for articles)
- [x] It's in English

### CODE REVIEW

**Comment by levtatz** [comment]
lol then why keep trump forest?

**Comment by bizz84** [comment]
@levtatz oh man, I can see it's going to be fun managing this project 😅

On one side, not including links that have a political nature may keep this project unbiased.

On the other side, a project with a provocative name like Trump Forest accomplishes a desirable goal (reforestation), and it could be argued that it uses a click bait for the common good.

**Comment by levtatz** [comment]
i agree with you

but i also think removing 350.org is not a good idea

**Comment by bizz84** [comment]
I'm open to all suggestions. There is some interesting ongoing discussion here:
https://news.ycombinator.com/item?id=15148860#15151320

I'll see what the general consensus is, and try to act accordingly.

Once the dividing line for in or out is clearer, I will document this in the README.

**Comment by bizz84** [comment]
@levtatz Prepared this as a starting point: #33.

Will move forward from there.

**Comment by levtatz** [comment]
thanks, i like this project

**Comment by bizz84** [comment]
I just created a Gitter channel for this project.

You can join here if you're interested: https://gitter.im/SustainableEarth

**Pull request merged**
